model:
  _target_: models.dcgan.DCGAN
  latent_dim: 128
  g_lr: 0.003
  d_lr: 0.0001
  b1: 0.7
  b2: 0.999

datamodule:
  _target_: datasets.mnist_datamodule.MNISTDataModule
  batch_size: 128
  train_val_ratio: 0.9
  num_workers: 4

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 100
  accelerator: gpu
  devices: auto

data_dir: data
