model:
  _target_: models.vae.VAE
  latent_dim: 128
  lr: 0.0001
  b1: 0.8
  b2: 0.999

datamodule:
  _target_: datasets.mnist_datamodule.MNISTDataModule
  batch_size: 128
  train_val_ratio: 0.9
  num_workers: 8

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 200
  accelerator: gpu
  devices: auto

callbacks:
  image_logger:
    _target_: utils.callbacks.ImageLoggerVAE
    num_samples: 4
    num_epochs: 5
  tqdm_pbar:
    _target_: pytorch_lightning.callbacks.progress.TQDMProgressBar
    refresh_rate: 20

data_dir: data
